### ISSUE TITLE
ILI9342 support

### ISSUE THREAD

**Issue by belm0** [codewitch-honey-crisis/gfx_libraries#2]
I've yet to evaluate gfx for my project, but just a light suggestion to support ILI9342, which is in the popular M5Stack Core / Core2.

I did get the demo working on a TTGO (on Arduino IDE) after much commotion-- I need to get on board with platformIO.

By the way, `Maziro.h` has a UTF-8 BOM header which upset the compiler.

**Comment by codewitch-honey-crisis** [comment]
Thanks for letting me know about the BOM. I believe the ILI9341 driver *should* work with the M5Stack. I have not tried it yet however, since I don't own an M5. I do know the M5 mounts the screen upside down so the rotation setting is opposite.
